[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "theory adult joy relief salt install various betray mountain blush beyond adjust tortoise total twelve behind club film door blossom switch ball gaze because"
